### ISSUE TITLE
Allow Full HTML support for Mailings

### ISSUE THREAD

**Issue by dachser-pb** [ibm-apiconnect/devportal#11]
Dear APIC Developer team,

would it be possible to allow "Full HTML" also for the mail_subscribers component?

I am referring to this piece of code:
https://github.com/ibm-apiconnect/devportal/blob/9c5985ea2e7434794b8ca0e42a1008596f563ba6/mail_subscribers/src/Wizard/Mail/EnterContentStep.php#L102

Would help us a lot in composing mailings that respect our CI guidelines.

BR, Patrick

**Comment by redlanne** [comment]
Hi Patrick,
Whilst this is potentially possible to allow this in the filter field, there are no guarantees that it would actually send full html.  The reason it is set like this is in order to prevent things such as attaching files as we know this won't work due to APIM's email sender.

What is it specifically that you want to do - you mention your CI guidelines.

best regards,
Anne

**Comment by dachser-pb** [comment]
Hi anne,
thank you for the prompt reaction.
To give you an impression of what our last mailing that we sent to the developer organizations using an external tool looked like here a screenshot
![image](https://user-images.githubusercontent.com/74193758/98936293-10a08c80-24e5-11eb-9ad4-a2effe2e1d60.png)

What I would like to achive
- use colors (e.g. background of the header and footer)
- specify Font Familys. The test mail i just sent on APIC v10 is actually rendered like this in my mail client:
![image](https://user-images.githubusercontent.com/74193758/98936765-b0f6b100-24e5-11eb-91b3-4f5f9d19cc69.png)

By the way - Is it possible to specify the sender's address?

**Comment by chrisdudley** [comment]
The sender address will be the one set in the cloud manager in apim.

**Comment by dachser-pb** [comment]
Hello Anne,
do you have any update on my request?
Thanks a lot.

**Comment by redlanne** [comment]
As things stand we will need an RFE to get this to work as fully as you need - full html allows a load of things we know won't work.

**Comment by dachser-pb** [comment]
So is there something I can do? Sorry I am not so used to your internal processes. If so it would be great if you tell me what to in order to get this started.

**Comment by chrisdudley** [comment]
You can raise an RFE (Request for Enhancement) here: https://www.ibm.com/developerworks/rfe/

Its not as simple as just allowing full_html because full_html would allow you to attach files etc, and we know that's not going to work, so it would possibly need a new input profile that allows all the styling etc you want but does not allow options that aren't going to work. 
But even then I am not sure that will be sufficient since if you look at the example email you gave it likely either references a CSS file on a public webserver or it will inline a whole load of CSS. Neither of which are operations a WYSIWYG editor is going to really let you do for security reasons (inline styles are simply not allowed in the WYSIWYG editor and I am not sure that is configurable).

That's why we'd need an RFE to justify the investment it would take on our side to look into this.
