### ISSUE TITLE
Remove "Reset" Button from Client ID  in Apps page.

### ISSUE THREAD

**Issue by fsofronis** [ibm-apiconnect/devportal#2]
Hi all,

I was wondering if there is any chance to remove the Reset button from the Application page in IBM Dev Portal.
The reason is we want to address each application to specific Client ID and we don't want developers to reset their Client IDs

**Comment by chrisdudley** [comment]
You could use CSS to simply hide the button.
You could override the application node template by copying the template to the templates directory of your custom theme and then you can simply remove the link from the template.
The risk in overriding templates is when we add new features you need to manually update your copy of the template too in order to pick them up.
